### ISSUE TITLE
Crate doesn't build from vendored tarball.

### ISSUE THREAD

**Issue by cameronfyfe** [khonsulabs/watchable#1]
When calling `cargo vendor` for a package that depends on `watchable`, the build will fail due to `src/.crate-docs.md` not being included in the vendored tarball, but being required by an `!include` in `src/lib.rs`.

See https://github.com/NixOS/nixpkgs/pull/276099

**Comment by ecton** [comment]
I believe this is fixed in v1.1.2. Thank you for reporting this!
